# Generated by Django 5.2.8 on 2025-12-11 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_answer_question_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='created_add',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
