# Generated by Django 5.2.8 on 2025-12-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_created_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='position',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(default='Option', max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='position',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(default='Your Question', max_length=300),
        ),
    ]
