# Generated by Django 5.2.8 on 2026-01-04 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_answer_position_alter_answer_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='created_add',
            new_name='created_at',
        ),
    ]
