# Generated by Django 5.2.8 on 2026-01-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_rename_created_add_quiz_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='question',
            name='timelimit',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('quiz', 'position')},
        ),
    ]
