# Generated by Django 6.0.1 on 2026-01-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_question_position_quizattempt_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='quizzer_name',
            field=models.CharField(default='anonymous', max_length=300),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(default='', max_length=300),
        ),
    ]
