# Generated by Django 6.0.2 on 2026-02-15 21:39

import quiz.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quizattempt_quizzer_name_alter_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='admin_id',
            field=models.CharField(default=quiz.utils.generate_admin_id, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='public_id',
            field=models.CharField(default=quiz.utils.generate_public_id, max_length=6, unique=True),
        ),
    ]
