# Generated by Django 6.0.2 on 2026-02-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_quiz_admin_id_alter_quiz_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='guided_current_question',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
