# Generated by Django 6.0.3 on 2026-04-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_quiz_guided_current_question'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('attempt', 'question')},
        ),
    ]
